### ISSUE TITLE
Segfault when providing expression on command line

### ISSUE THREAD

**Issue by dschopf** [Qalculate/qalculate-gtk#107]
When calling `./qalculate-gtk "2+2"` I get a segfault. This is with d406f71 and libqalculate 3.3.0.

Here is a backtrace:
```
#0  0x0000555555630eb5 in setResult(Prefix*, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, bool)
    (prefix=0x0, update_history=true, update_parse=true, force=<optimized out>, transformation="", stack_index=<optimized out>, register_moved=false) at callbacks.cc:7452
#1  0x0000555555639e22 in execute_expression(bool, bool, MathOperation, MathFunction*, bool, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (force=<optimized out>, do_mathoperation=<optimized out>, op=OPERATION_ADD, f=<optimized out>, do_stack=<optimized out>, stack_index=<optimized out>, execute_str="", str="2+2", check_exrates=true)
    at /usr/include/c++/9.1.0/bits/basic_string.h:263
#2  0x0000555555643b00 in update_mb_to_menu() () at /usr/include/c++/9.1.0/bits/char_traits.h:300
#3  0x00005555555ad935 in create_button_menus() () at interface.cc:987
#4  0x000055555559d781 in create_application(_GtkApplication*) (app=<optimized out>) at main.cc:215
#5  0x000055555559e3f8 in qalculate_command_line(GtkApplication*, GApplicationCommandLine*) (app=0x5555557b80f0, cmd_line=<optimized out>) at main.cc:385
#6  0x00007ffff54be6d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#7  0x00007ffff54be0a0 in ffi_call () at /usr/lib/libffi.so.6
#8  0x00007ffff707944e in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff706fcaa in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff705d706 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff7060e2c in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff7062700 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff715ad67 in  () at /usr/lib/libgio-2.0.so.0
#14 0x00007ffff715d9e2 in  () at /usr/lib/libgio-2.0.so.0
#15 0x00007ffff715d536 in g_application_run () at /usr/lib/libgio-2.0.so.0
#16 0x000055555559a625 in main(int, char**) (argc=2, argv=0x7fffffffdeb8) at main.cc:428
```
Looks like view_thread in callbacks.cpp:7452 is not valid yet.

**Comment by hanna-kn** [comment]
Fixed.
