### ISSUE TITLE
Search provider crashes a lot (perhaps related to glib 2.76 update)

### ISSUE THREAD

**Issue by swsnr** [Qalculate/qalculate-gtk#473]
With qalculate-gtk 4.6.0 on Arch Linux the search provider crashes a lot, apparently every time I search.  Unfortunately I don't know when this behaviour started, since I haven't used since quite a while.  But today I noticed that the search provider no longer works and discovered that it generated an awful lot of core dumps, i.e. almost 70 just today.

```console
$ qalculate-gtk --version
4.6.0
$ coredumpctl list --since=2023-04-02 /usr/lib/qalculate-search-provider --no-legend | wc -l
68
$ coredumpctl list /usr/lib/qalculate-search-provider  -n1
TIME                          PID   UID   GID SIG     COREFILE EXE                                SIZE
Mon 2023-03-13 23:02:06 CET 44331 60105 60105 SIGSEGV missing  /usr/lib/qalculate-search-provider    -
$ rg '\[ALPM\].*qalculate' /var/log/pacman.log | tail -n2
[2023-03-08T20:08:19+0100] [ALPM] upgraded libqalculate (4.5.1-1 -> 4.6.0-1)
[2023-03-08T20:08:19+0100] [ALPM] upgraded qalculate-gtk (4.5.1-1 -> 4.6.0-1)
$ rg '2023-03-13T.*\[ALPM\].*glib2.*' /var/log/pacman.log | rg glib | wl-copy
[2023-03-13T22:07:11+0100] [ALPM] upgraded glib2 (2.74.6-1 -> 2.76.0-1)
[2023-03-13T22:07:11+0100] [ALPM] upgraded glib2-docs (2.74.6-1 -> 2.76.0-1)
```

As you can see the oldest coredump I have is from 2023-03-13, i.e. a few days after the update to 4.6.0.  However, according to my pacman.log glib2 was upgraded to 2.76 just about an hour before the first crash, so perhaps the crash is related to the slice allocator removal in glib2 which seems to have had quite a bit of fallout throughout the ecosystem (see https://gitlab.gnome.org/GNOME/glib/-/issues/2937).

Running `bt full` in gdb for the most recent crash a few minutes ago gives the following stacktrace:

```
#0  g_type_check_instance_is_fundamentally_a (type_instance=0x7f05a0003e10, fundamental_type=0x50)
    at ../glib/gobject/gtype.c:4166
        node = <optimized out>
#1  0x00007f05b11ec2ae in g_object_unref (_object=0x7f05a0003e10) at ../glib/gobject/gobject.c:3807
        _g_boolean_var_133 = <optimized out>
        object = 0x7f05a0003e10
        old_ref = <optimized out>
        __func__ = "g_object_unref"
#2  0x00007f05b10cf09d in g_source_callback_unref (cb_data=0x7f05a00023f0) at ../glib/glib/gmain.c:1742
        callback = 0x7f05a00023f0
#3  g_source_callback_unref (cb_data=0x7f05a00023f0) at ../glib/glib/gmain.c:1735
        callback = 0x7f05a00023f0
#4  0x00007f05b10d68b0 in g_source_destroy_internal (source=0x7f05a0003f30, context=0x55c2dfbf0f40, have_lock=1)
    at ../glib/glib/gmain.c:1407
        tmp_list = <optimized out>
        old_cb_data = 0x7f05a00023f0
        old_cb_funcs = 0x7f05b11c8380 <g_source_callback_funcs>
#5  0x00007f05b10d9670 in g_main_dispatch (context=0x55c2dfbf0f40) at ../glib/glib/gmain.c:3490
        dispatch = <optimized out>
        prev_source = 0x0
        begin_time_nsec = 15883927052505
        was_in_call = 0
        user_data = 0x7f05a0003e10
        callback = 0x7f05b132e160 <call_in_idle_cb>
        cb_funcs = 0x7f05b11c8380 <g_source_callback_funcs>
        cb_data = 0x7f05a00023f0
        need_destroy = 1
        source = 0x7f05a0003f30
        current = 0x55c2dfd53b70
        i = 0
#6  g_main_context_dispatch (context=0x55c2dfbf0f40) at ../glib/glib/gmain.c:4200
#7  0x00007f05b1136219 in g_main_context_iterate.constprop.0
    (context=0x55c2dfbf0f40, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4276
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = 3
        allocated_nfds = <optimized out>
        fds = <optimized out>
        begin_time_nsec = 15883927048533
#8  0x00007f05b10d81a2 in g_main_context_iteration (context=context@entry=0x55c2dfbf0f40, may_block=may_block@entry=1)
    at ../glib/glib/gmain.c:4343
        retval = <optimized out>
#9  0x00007f05b13073de in g_application_run (application=0x55c2dfb72120, argc=<optimized out>, argv=0x7ffd179345b8)
    at ../glib/gio/gapplication.c:2573
        arguments = 0x55c2dfbd8a10
        status = 0
        context = 0x55c2dfbf0f40
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#10 0x000055c2de4413d7 in main(int, char**) (argc=1, argv=0x7ffd179345b8)
    at /usr/src/debug/qalculate-gtk/qalculate-gtk-4.6.0/src/searchprovider.cc:673
        app = 0x55c2dfb72120
        status = <optimized out>
        gstr_file = <optimized out>
        file = <optimized out>
        line = "ignore_locale=0\n\000n_type=2\n", '\000' <repeats 2702 times>...
        stmp = ""
```

Note that I'm not quite familiar with C and obtain the above backtrace only by following instructions on https://wiki.archlinux.org/title/Debugging/Getting_traces

Should you need more information please tell me, but please bear with me if I don't immediately understand what I need to do 😊

**Comment by hanna-kn** [comment]
Fixed (boolean return value where required in callback functions).

**Comment by Jmennius** [comment]
> Fixed (boolean return value where required in callback functions).

Can we have this released then? 😄 
Thanks!

**Comment by hanna-kn** [comment]
> Can we have this released then? 

On Monday.
